apiVersion: lag0.com.br/v1
kind: ClusterLimitRange
metadata:
  name: default-cluster-lr
spec:
  ignoredNamespaces:
  - kube-system
  - kube-public
  - flux-system
  - system
  - domain-vars
  # applyNamespaces:
  # - dev
  # - staging
  limits:
  - type: Container
    max:
      ephemeral-storage: "2Gi"
      # min:
      #   cpu: "200m"
      #   memory: "256Mi"
      defaultLimit:
        ephemeral-storage: "1Gi"
      defaultRequest:
        ephemeral-storage: "200Mi"
      # maxLimitRequestRatio:
#   cpu: "4"
