apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lag0.com.br
  resources:
  - clusterlimitranges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lag0.com.br
  resources:
  - clusterlimitranges/finalizers
  verbs:
  - update
- apiGroups:
  - lag0.com.br
  resources:
  - clusterlimitranges/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["limitranges"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
